### ISSUE TITLE
Support of access restrictions (acl)

### ISSUE THREAD

**Issue by Otto-AA** [jeff-zucker/solid-rest#1]
Is there some kind of .acl support intended in the future?

I don't quite know yet, how authentication would work, but I guess that it could be done to some extent (e.g. for apps with the origin).

**Comment by jeff-zucker** [comment]
That may be possible in some kinds of storage, but with localStorage, I don't think we can actually prevent an app from reading what it wrote or prevent it from writing.  In nodejs one assumes that  the user is the owner.   I guess .acl would be useful for mocking but to get them to work would be pretty darn hard I would think.

**Comment by jeff-zucker** [comment]
Solid-rest storage is always, by definition, owned by the user of the app.  Only the owner can run shell scripts in a local file system.  Only the owner can access localStorage.  So access control is essentially meaningless in these contexts, therefore closing this issue.  If the person has got control of your shell or your browser, the horse is already gone and it's too late to lock the barn door.

**Comment by Otto-AA** [comment]
I see that this is not relevant now and in the near future. It could be useful when the app which uses solid-rest is placed in a different context than the one which uses data. For example a browser extension which makes dropbox requests solid-compatible but still wants some kind of authentication and access control. But I guess that we are far enough away from this to keep this issue closed :D

**Comment by jeff-zucker** [comment]
Good point about Dropbox.  That would make a great use of Solid-Rest, and as you say, would require at a minimum authentication (could maybe mimic acl:origin controls for the entire Dropbox folder) and then, I'm not sure if it would be worth it to map Dropbox per-resource restrictions to individual .acl files, but it would be worth considering.
