### ISSUE TITLE
Implement Dropbox as a Solid-accessible storage

### ISSUE THREAD

**Issue by jeff-zucker** [jeff-zucker/solid-rest#18]
@Otto-AA and I both thought of Dropbox as a natural fit for Solid-Rest.  All that needs to be done is implement a thin layer similar to [solid-rest/file](https://github.com/jeff-zucker/solid-rest/blob/master/src/file.js) or [solid-rest/localStorage](https://github.com/jeff-zucker/solid-rest/blob/master/src/localStorage.js) and coordinate with Dropbox's native access control mechanisms.   Anyone that wants to give this a try, please get in touch.  I'd be glad to help but can't fully take this on at the moment.

**Comment by theWebalyst** [comment]
Nice idea. You might take a look at remoteStorage.io which is similar to Solid. They implement Dropbox and Google drive backends as well as the RS server. I made an RS backend for SAFE and found it useful to look at their different implementations.

**Comment by jeff-zucker** [comment]
I have now implemented this through browserFS.  Haven't got it completely working yet.  The problem is on the Dropbox side, so once I (or someone else) figures that out, it should work.

**Comment by jeff-zucker** [comment]
This has now been accomplished by supporting BrowserFS filesystems which includes Dropbox.  I haven't tried it myself but I see no reason it shouldn't work.
