### ISSUE TITLE
disallow creation of links with POST

### ISSUE THREAD

**Issue by bourgeoa** [jeff-zucker/solid-rest#28]
POST MUST not be used to create linked resources and should return 403

`When a `PUT` or `PATCH` method request targets an auxiliary resource, the
server MUST create or update it. When a `POST` method request with the `Slug`
header targets an auxiliary resource, the server MUST respond with the `403`
status code and response body describing the error.
[[Source](https://github.com/solid/specification/issues/42#issuecomment-616688848)]`

**Comment by jeff-zucker** [comment]
Solved in #31.
