### ISSUE TITLE
file do not pass tests since commits from july 29

### ISSUE THREAD

**Issue by bourgeoa** [jeff-zucker/solid-rest#29]
@jeff-zucker Since last commits tests do not pass for `file://`
- Testing for parent folder exists `getObjectType() `always create the missing folders if not exists and return true
- I rolled manually back the last commits and tests still fails
- i tried different code for `getObjectType()` and always run in the same difficulties

I am running node.js v14.6 and I did not change version for a long time.

Tests for local storage `ls://` succeeds all

**Comment by jeff-zucker** [comment]
I am current with the master and all tests pass for me.21/21 for both ls and file.  Are you sure you have the most recent master?

**Comment by bourgeoa** [comment]
thanks solved.

I had a problem with npm dependencies.
I cloned from repo, rebuild from scratch and it works
