### ISSUE TITLE
Missing built files in npm releases, incorrect specification in package.json

### ISSUE THREAD

**Issue by CxRes** [jeff-zucker/solid-rest#30]
The built files corresponding to `module` and `browser` properties are not being created by upon a npm release. I cannot identify why this is the case though, given build scripts are defined.

Also, per my understanding a `module` release is unnecessary given the code is still commonJS. It is also confusing for the bundler which given in solid-file-client `module` points to the unbuilt source (correctly, since that is esm); here it is `main` that points to unbuilt source and `module` points to a lib version which is missing but if it existed would be redundant.

**Comment by Otto-AA** [comment]
> The built files corresponding to module and browser properties are not being created by upon a npm release. I cannot identify why this is the case though, given build scripts are defined.

Should be fixed by #36 

> It is also confusing for the bundler which given in solid-file-client module points to the unbuilt source (correctly, since that is esm)

First of, the esm syntax is `import { foo } from 'bar'`, rest.js uses `const { foo } = require('bar')`, so I don't think this is ESM. If I would include the rest.js file directly in a webpage it wouldn't work because of the `require`.

Apart from this I don't know what the proper configuration should be here. It seems that "module" should point to a ESM version, but I'm not sure how we should do it here.

**Comment by CxRes** [comment]
> Apart from this I don't know what the proper configuration should be here. It seems that "module" should point to a ESM version, but I'm not sure how we should do it here.
Just remove the `module` property! Alternatively (in the long run), just use esm imports/exports. Webpack won't mind!

**Comment by Otto-AA** [comment]
Ok, I've also removed this property in the PR

**Comment by jeff-zucker** [comment]
See my comments/questions at https://github.com/jeff-zucker/solid-rest/pull/36#issuecomment-667544740

**Comment by jeff-zucker** [comment]
I believe this is now fixed with  my https://github.com/jeff-zucker/solid-rest/commit/9b710342b0ff9415b0fda9ab28030771fc4efacf.  If it looks good, let me know and I'll npm it.

**Comment by CxRes** [comment]
Couple of pedantic things:
+ some dot files are missing newlines at the end (I set up the editor to take care of this automatically).
+ keyword "file systems" should be "file system" imho (or at least "file system" should be a keyword since people will search for the singular rather than its plural more often).

Also do you really want to include bundles in the github repo (as opposed to keeping them in npm bundles only) ie removal of `bundles` from gitignore?

**Comment by jeff-zucker** [comment]
> * some dot files are missing newlines at the end (I set up the editor to take care of this automatically).
> * keyword "file systems" should be "file system" imho (or at least "file system" should be a keyword since people will search for the singular rather than its plural more often).

Okay, thanks, will fix.
 
> Also do you really want to include bundles in the github repo (as opposed to keeping them in npm bundles only) ie removal of `bundles` from gitignore?

Is there harm in storing them on github?  Because people won't be able to experiment with BrowserFS and Dropbox without them.

**Comment by CxRes** [comment]
> Is there harm in storing them on github? Because people won't be able to experiment with BrowserFS and Dropbox without them.

No harm, just that we have a cleaner separation of responsibilities ie github as code repo and npm as artifact store! 

I am not following the new developments closely but I do not follow why people will not be able to experiment with BrowserFS and Dropbox? Wouldn't one install from npm or if one were to clone the repo, wouldn't one build it anyway? Am I right in guessing that you want people to `npm install github:jeff-zucker/solid-rest`.

I am closing the issue since it seems solved otherwise!!!!

**Comment by jeff-zucker** [comment]
I think I tried building them from the cloned repo and failed.  But maybe I overlooked something.  I'll try again and also look for a CDN.  I agree either of those solutions are cleaner,
